/*테이블 검색 */
SELECT 
    TC.OWNER AS "Owner",
    TC.TABLE_NAME AS "테이블ID",
    TAB_COMMENTS.COMMENTS AS "테이블명",
    TC.COLUMN_NAME AS "컬럼ID",
    CDC.COMMENTS AS "컬럼명",
    CASE WHEN TC.COLUMN_NAME IN (
        SELECT COLS.COLUMN_NAME
        FROM ALL_CONSTRAINTS CONS
        JOIN ALL_CONS_COLUMNS COLS ON CONS.CONSTRAINT_NAME = COLS.CONSTRAINT_NAME
        WHERE CONS.CONSTRAINT_TYPE = 'P'
        AND COLS.TABLE_NAME = TC.TABLE_NAME
        AND COLS.OWNER = TC.OWNER
    ) THEN 'Y' ELSE 'N' END AS "PK여부"    
FROM ALL_TAB_COLUMNS TC
LEFT JOIN ALL_COL_COMMENTS CDC ON TC.OWNER = CDC.OWNER AND TC.TABLE_NAME = CDC.TABLE_NAME AND TC.COLUMN_NAME = CDC.COLUMN_NAME
LEFT JOIN ALL_TAB_COMMENTS TAB_COMMENTS ON TC.OWNER = TAB_COMMENTS.OWNER AND TC.TABLE_NAME = TAB_COMMENTS.TABLE_NAME
WHERE 1=1 
--AND TC.TABLE_NAME = 'TB_CD_CENT_MM_CLOS_MT' -- 테이블ID 
--AND TAB_COMMENTS.COMMENTS = 'TB_CD_CENT_MM_CLOS_MT' -- 테이블명
--AND TC.COLUMN_NAME = 'TB_CD_CENT_MM_CLOS_MT' -- 컬럼ID
--AND CDC.COMMENTS = 'TB_CD_CENT_MM_CLOS_MT' -- 컬럼명
ORDER BY TC.OWNER, TC.TABLE_NAME;

/* 프로시저 조회 */
SELECT 
   OBJECT_NAME || '(' || TO_CHAR(LAST_DDL_TIME,'YYYYMMDD_HH24MISS') ||')' AS PROCEDURE_NAME,
   CASE WHEN STATUS ='VALID' THEN '정상' ELSE '비정상' END AS PROCEDURE_STATUS 
FROM DBA_OBJECTS 
WHERE OWNER = 'LM_ADM'
  AND OBJECT_TYPE = 'PROCEDURE' 
  AND TO_CHAR(LAST_DDL_TIME,'YYYYMMDD') >  '20230402' 
ORDER BY PROCEDURE_STATUS DESC, PROCEDURE_NAME ASC;


